---
# Install cacti on the Raspberry Pi.
# https://cacti.net/

- hosts: all
  gather_facts: yes

  tasks:
    - name: Install packages
      become: yes
      apt:
        update-cache: yes
        cache_valid_time: 3600
        pkg:
          - cacti
          - python3-bs4

    - name: Add device
      become: yes
      command:
        argv:
          - /usr/share/cacti/cli/add_device.php
          - --description=Gateway
          - --ip={{ ansible_default_ipv4.gateway }}
          - --template=0
          - --version=0
          - --ping_method=icmp

    - name: Install script
      become: yes
      copy:
        src: files/modem_power.py
        dest: /usr/local/sbin/modem_power.py
        mode: 0755

...
