---
# Install cacti on the Raspberry Pi.
# https://cacti.net/

- hosts: all
  gather_facts: yes

  tasks:
    - name: Install packages
      become: yes
      apt:
        update-cache: yes
        cache_valid_time: 3600
        pkg:
          - cacti
          - python3-bs4

    - name: Copy files
      become: yes
      copy:
        src: "files/{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - { src: modem_power.py, dest: /usr/local/sbin/, mode: '0755' }
        - { src: cacti_graph_template_modem_power.xml, dest: /tmp/, mode: '0644' }

    - name: Import template
      become: yes
      command:
        argv:
          - /usr/share/cacti/cli/import_template.php
          - --filename=/tmp/cacti_graph_template_modem_power.xml

    - name: Add device
      become: yes
      command:
        argv:
          - /usr/share/cacti/cli/add_device.php
          - --description=Gateway
          - --ip={{ ansible_default_ipv4.gateway }}
          - --template=0
          - --version=0
          - --ping_method=icmp

    - name: Remove files
      become: yes
      file:
        path: /tmp/cacti_graph_template_modem_power.xml
        state: absent

...
