# Emulate Raspberry Pi OS
FROM debian

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get --yes install \
        openssh-server \
        python3 \
        sudo \
    && rm --recursive --force /var/lib/apt/lists/*

# Configure ssh service on first run
RUN service ssh start

# Unprivileged user
RUN adduser pi
RUN echo pi:raspberry | chpasswd
RUN echo "pi ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/pi
USER pi
WORKDIR /home/pi
