# Development container for ansible
FROM debian

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get --yes install \
        ansible \
        git \
        openssh-client \
        sshpass \
    && rm --recursive --force /var/lib/apt/lists/*

# Unprivileged user
RUN adduser --disabled-password user
USER user
WORKDIR /home/user
