---
# Configure the Raspberry Pi to use external USB storage.
# https://www.raspberrypi.org/documentation/configuration/external-storage.md

- hosts: all
  gather_facts: no

  tasks:
    - name: Install packages
      become: yes
      apt:
        update-cache: yes
        cache_valid_time: 3600
        pkg:
          - exfat-fuse
          - hfsplus
          - ntfs-3g

    - name: Discover devices
      command: lsblk --json --output PARTUUID,LABEL,FSTYPE
      changed_when: no
      register: lsblk

    - name: For each device ...
      vars:
        result: "{{ lsblk.stdout | from_json }}"
      include_tasks: tasks/automatic-mount.yml
      loop: "{{ result.blockdevices }}"
      when:
        - item.partuuid not in [ None ]
        - item.fstype in [ "exfat", "hfsplus", "ntfs", "vfat" ]
        - item.label not in [ None, "boot", "EFI", "rootfs" ]

    - name: Install script
      become: yes
      copy:
        src: files/usb-power.sh
        dest: /usr/local/sbin/usb-power.sh
        mode: 0755

...
