---
# Install homeassistant on the Raspberry PI
# https://www.home-assistant.io/installation/raspberrypi-other/#docker-compose
# https://docs.docker.com/engine/install/linux-postinstall/
# https://github.com/bm1549/home-assistant-frigidaire#manual

- hosts: "{{ ansible_limit | default('homeassistant.local') }}"
  gather_facts: no

  tasks:
    - name: Install packages
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg:
          - docker.io
          - docker-compose

    - name: Configure users and groups
      become: yes
      user:
        name: pi
        groups: docker
        append: true

    - name: Copy files
      become: yes
      copy:
        src: "files/{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: compose.yaml, dest: /usr/local/etc/homeassistant/ }
        - { src: 60-otbr-accept-ra.conf, dest: /etc/sysctl.d/ }
        - { src: 60-otbr-ip-forward.conf, dest: /etc/sysctl.d/ }

    - name: Download Frigidaire integration
      become: yes
      unarchive:
        remote_src: yes
        src: https://github.com/bm1549/home-assistant-frigidaire/archive/refs/heads/main.zip
        dest: /tmp/

    - name: Install Frigidaire integration
      become: yes
      copy:
        remote_src: yes
        src: /tmp/home-assistant-frigidaire-main/custom_components/frigidaire
        dest: /usr/local/etc/homeassistant/custom_components/

    - name: Load settings from all system configuration files
      become: yes
      command: sysctl --system

    - name: Start services
      become: no
      command:
        chdir: /usr/local/etc/homeassistant/
        cmd: "{{ item }}"
      loop:
        - docker compose down
        - docker compose pull
        - docker compose up --detach

    - name: Clean up
      become: yes
      file:
        path: /tmp/home-assistant-frigidaire-main
        state: absent

...
