---
# Install pihole on the Raspberry Pi.
# https://pi-hole.net/
# https://discourse.pi-hole.net/t/installing-pi-hole-on-existing-apache-server/43968

- hosts: "{{ ansible_limit | default('raspi') }}"
  gather_facts: no

  vars:
    latest: yes

  tasks:
    ############################################################################
    - name: Install latest version of pihole
      when: latest
      block:

        - name: Copy configuration file
          become: yes
          copy:
            src: files/pihole.toml
            dest: /etc/pihole/
            mode: 0644

        - name: Fetch install script
          get_url:
            url: https://install.pi-hole.net
            dest: /tmp/basic-install.sh
            mode: a+x

        - name: Run install script
          become: yes
          command: /tmp/basic-install.sh --unattended

        - name: Reset password
          become: yes
          command: echo | pihole setpassword

    ############################################################################
    - name: Install pihole v5
      when: not latest
      block:

        - name: Install packages
          become: yes
          apt:
            update-cache: yes
            cache_valid_time: 3600
            pkg:
              - libapache2-mod-php
              - php-sqlite3

        - name: Copy configuration file
          become: yes
          copy:
            src: files/setupVars.conf
            dest: /etc/pihole/
            mode: 0644

        - name: Copy install script
          copy:
            src: files/basic-install-v5.sh
            dest: /tmp/
            mode: 0755
      
        - name: Run install script
          become: yes
          command: /tmp/basic-install-v5.sh --unattended

        - name: Update group membership
          become: yes
          user:
            name: www-data
            append: true
            groups: [ pihole ]

        - name: Disable automatic version update checks
          become: yes
          replace:
            path: /etc/cron.d/pihole
            regexp: '^([^#].*pihole updatechecker.*)'
            replace: '# \g<1>'

        - name: Remove information about latest version
          become: yes
          lineinfile:
            path: /etc/pihole/versions
            state: absent
            search_string: GITHUB_

    ############################################################################
    # https://raspberrypi.stackexchange.com/questions/96606/make-iw-wlan0-set-power-save-off-permanent
    - name: Disable WiFi power save mode
      become: yes
      command: nmcli connection modify "43 Payne" wifi.powersave disable

...
