---
# Improve security.
# Configure the Raspberry Pi to require key-based authentication for ssh.
# Enable automatic upgrades.
# https://www.raspberrypi.org/documentation/configuration/security.md
# https://wiki.debian.org/UnattendedUpgrades

- hosts: "{{ ansible_limit | default('raspi') }}"
  gather_facts: no

  tasks:
    - name: Add authorized keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ lookup('env','HOME') }}/.ssh/*.pub"
        - "files/*.pub"

    - name: Verify key-based authentication
      command: ssh -o PasswordAuthentication=no {{ ansible_user }}@{{ inventory_hostname }} true
      delegate_to: localhost
      changed_when: no

    - name: Disable password logins
      become: yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?{{ item.option }} "
        line: "{{ item.option }} {{ item.value }}"
      with_items:
        - { option: 'ChallengeResponseAuthentication', value: 'no' }
        - { option: 'PasswordAuthentication', value: 'no' }
        - { option: 'UsePAM', value: 'no' }

    - name: Uninstall packages
      become: yes
      apt:
        update-cache: yes
        cache_valid_time: 3600
        pkg:
          - userconf-pi
        state: absent
        purge: yes

    - name: Enable automatic updates
      become: yes
      apt:
        update-cache: yes
        cache_valid_time: 3600
        pkg:
          - unattended-upgrades

...
