---
# Configure the Raspberry Pi to have additional swap space.
# https://pimylifeup.com/raspberry-pi-swap-file/
# https://www.kernel.org/doc/html/latest/admin-guide/mm/zswap.html

- hosts: all
  gather_facts: no

  tasks:
    - name: Disable absolute swap size
      become: yes
      lineinfile:
        path: /etc/dphys-swapfile
        backrefs: yes
        regexp: '^#?(CONF_SWAPSIZE=.*)$'
        line: '#\1'

    - name: Enable ZSWAP
      include_tasks: tasks/cmdline.yml
      loop:
        - { option: 'zswap.enabled', value: 'yes' }

...
