---
# Configure /etc/fstab to automatically mount a storage device.
# Expects item.lable, item.partuuid, and item.fstype to be defined.
 
- name: Create mount point
  become: yes
  file:
    path: /mnt/{{ item.label }}
    state: directory

- name: Update fstab
  become: yes
  lineinfile:
    path: /etc/fstab
    line: >
      PARTUUID={{ item.partuuid }} 
      /mnt/{{ item.label.replace(' ','\040') }} 
      {{ item.fstype }} 
      defaults,auto,nofail,rw,users,umask=000  0  0
    regexp: '^PARTUUID={{ item.partuuid }}'
    insertafter: '^PARTUUID='

...
