# https://openthread.io/guides/border-router/build-docker
# https://raw.githubusercontent.com/openthread/ot-br-posix/refs/heads/main/etc/docker/border-router/setup-host

net.ipv6.conf.all.forwarding = 1
net.ipv4.ip_forward = 1
