# https://ubuntu.com/server/docs/how-to/wireguard-vpn/vpn-as-the-default-gateway/

[Interface]
Address = XXX.XXX.XXX.1/24
ListenPort = 51820
PostUp = wg set %i private-key /etc/wireguard/%i.key
PostUp = sysctl net.ipv4.ip_forward=1
PostUp = iptables --append FORWARD --in-interface %i --jump ACCEPT
PostUp = iptables --append FORWARD --out-interface %i --jump ACCEPT
PostUp = iptables --table nat --append POSTROUTING --out-interface wlan0 --jump MASQUERADE
PostDown = iptables --table nat --delete POSTROUTING --out-interface wlan0 --jump MASQUERADE
PostDown = iptables --delete FORWARD --out-interface %i --jump ACCEPT
PostDown = iptables --delete FORWARD --in-interface %i --jump ACCEPT

[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
PresharedKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
AllowedIPs = XXX.XXX.XXX.2/32

[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
PresharedKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
AllowedIPs = XXX.XXX.XXX.3/32

[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
PresharedKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
AllowedIPs = XXX.XXX.XXX.4/32

[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
PresharedKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
AllowedIPs = XXX.XXX.XXX.5/32
